"""Descripción de la migración

Revision ID: 76e7937fca12
Revises: 49aa36461cd6
Create Date: 2025-02-03 18:12:48.349304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '76e7937fca12'
down_revision = '49aa36461cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the inspector object
    bind = op.get_bind()
    inspector = inspect(bind)

    # Check if the 'password_hash' column exists
    if 'password_hash' not in [col['name'] for col in inspector.get_columns('user')]:
        with op.batch_alter_table('user', schema=None) as batch_op:
            # Agregar la columna 'password_hash' sin restricciones de NULL
            batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
    
    # Establece un valor predeterminado para los registros existentes
    op.execute("UPDATE user SET password_hash = '' WHERE password_hash IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Cambiar la columna a 'NOT NULL' después de que los datos estén actualizados
        batch_op.alter_column('password_hash', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
